

###
### Reusable Fields and Components
###
################ Link
link_component: &link_component                
  - {required: false, label: "url", name: "url", widget: "string"}
  - {required: false, label: "newTab", name: "newTab", widget: "boolean", default: false}
  - {required: false, label: "text", name: "text", widget: "string"}
################ Meta
meta_component: &meta_component
  - {label: "Meta Title", name: "metaTitle", widget: "string"}
  - {required: false, label: "metaDescription:", name: "metaDescription:", widget: "text"}
  - {required: false, label: "twitterCardType:", name: "twitterCardType:", widget: "string", default: "summary"}
  - {required: false, label: "twitterUsername:", name: "twitterUsername:", widget: "string"}
  - {required: false, label: "shareImage", name: "shareImage", widget: "image"}
################ Description
desc_field: &desc_field {required: false, label: "label", name: "label", widget: "string"}
################ Label
label_field: &label_field {required: false, label: "description", name: "description", widget: "text"}
################ Title
title_field: &title_field {required: false, label: "title", name: "title", widget: "string"}
###
### Define Fields ***END***
###

backend:
  name: git-gateway
  branch: main # Branch to update

logo_url: 'https://www.aviertechnologies.com/assets/avier-logo.png'
media_folder: "public/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/uploads" # The src attribute for uploaded media
collections:
  - name: "page" 
    create: true
    folder: "_posts/page"
    format: 'json'
    label: "Page"
    slug: "{{fields.slug}}"
    fields:
      - label: "Metadata"
        name: "metadata"
        widget: "object"
        required: false
        fields: *meta_component
      - {required: false, label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - label: "Content Sections"
        name: "contentSections"
        widget: "list"
        typeKey: "contentSectionType"
        types:
          # Featured Row Content Section
          - label: "Featured Row"
            name: "featuredRow"
            widget: "object"
            fields:
              - {required: false, label: "Component", name: "__component", widget: "hidden", default: "sections.feature-rows-group"}
              - label: "Features"
                name: "features"
                widget: "list" 
                default: []
                fields:
                  - *title_field
                  - *desc_field
                  - label: "target link"
                    name: "link"
                    widget: "object"
                    fields: *link_component
          # Image Gallery Content Section
          - label: "Image Gallery"
            name: "imageGallery"
            widget: "object"
            fields:
              - {required: false, label: "Component", name: "__component", widget: "hidden", default: "sections.image-gallery"}
              - {required: false, label: "Title", name: "Title", widget: "string"}
              - {required: false, label: "ImagesPerLine", name: "ImagesPerLine", widget: "number"}
              - label: "imageWithLink"
                name: "imageWithLink"
                widget: "list"
                fields:
                  - {required: false, label: "imageUrl", name: "imageUrl", widget: "image"}
                  - label: "targetLink"
                    name: "targetLink"
                    widget: "object"
                    fields: *link_component
          # Rich Text Content Section
          - label: "Rich Text"
            name: "richText"
            widget: "object"
            fields:
              - {required: false, label: "Component", name: "__component", widget: "hidden", default: "sections.rich-text"}
              - {required: false, label: "Content", name: "content", widget: "text"}
          # Video Landing Page Content Section
          - label: "Video Landing Page"
            name: "videoLandingPage"
            widget: "object"
            fields:
              - {required: false, label: "Component", name: "__component", widget: "hidden", default: "sections.video-landing-page"}
              - *title_field
              - *label_field
              - *desc_field
              - {required: false, label: "smallTextWithLink", name: "smallTextWithLink", widget: "text"}
              - label: "videoURLs"
                name: "videoURLs"
                widget: "list"
                fields: *link_component
              - label: "InlineFeatures"
                name: "InlineFeatures"
                widget: "list"
                fields:
                  - *title_field
                  - *desc_field
                  - {required: false, label: "Target url", name: "url", widget: "string"}
                  - {required: false, label: "image", name: "image", widget: "image"}
          # Wide Hero Content Section
          - label: "Wide Hero"
            name: "wideHero"
            widget: "object"
            fields:
              - {required: false, label:"Component", name: "__component", widget: "hidden", default: "sections.wide-hero"}
          # Wide Video Content Section
          - label: "Wide Video"
            name: "wideVideo"
            widget: "object"
            fields:
              - {required: false, label:"Component", name: "__component", widget: "hidden", default: "sections.wide-video"}
              - *title_field
              - *label_field
              - *desc_field
              - {required: false, label: "youtubeEmbedUrl", name: "youtubeEmbedUrl", widget: "string"}
              - {required: false, label: "videoUrl", name: "videoUrl", widget: "string"}
              - {required: false, label: "richText", name: "richText", widget: "text"}
              - {required: false, label: "video", name: "video", widget: "hidden", default:""}
      - {required: false, label: "Status", name: "status", widget: "hidden", default: "published"}
