backend:
  name: git-gateway
  branch: main # Branch to update
logo_url: 'https://www.aviertechnologies.com/assets/avier-logo.png'
media_folder: "public/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/uploads" # The src attribute for uploaded media
collections:
  - name: "page" 
    create: true
    folder: "_posts/page"
    format: 'json'
    label: "Page"
    slug: "{{fields.slug}}"
    fields:
      - label: "Metadata"
        name: "metadata"
        widget: "object"
        required: false
        fields:
            - {label: "Meta Title", name: "metaTitle", widget: "string"}
            - {required: false, label: "metaDescription:", name: "metaDescription:", widget: "text"}
            - {required: false, label: "twitterCardType:", name: "twitterCardType:", widget: "string", default: "summary"}
            - {required: false, label: "twitterUsername:", name: "twitterUsername:", widget: "string"}
            - {required: false, label: "shareImage:", name: "shareImage:", widget: "image"}
      - {required: false, label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - label: "Content Sections"
        name: "contentSections"
        widget: "list"
        typeKey: "contentSectionType"
        types:
          # Featured Row Content Section
          - label: "Featured Row"
            name: "featuredRow"
            widget: "object"
            fields:
              - {required: false, label: "Component", name: "__component", widget: "hidden", default: "sections.feature-rows-group"}
              - label: "Features"
                name: "features"
                widget: "list" 
                default: []
                fields:
                  - {required: false, label: "title", name: "title", widget: "string"}
                  - {required: false, label: "description", name: "description", widget: "text"}
                  - label: "target link"
                    name: "link"
                    widget: "object"
                    fields:
                      - {required: false, label: "url", name: "url", widget: "string"}
                      - {required: false, label: "newTab", name: "newTab", widget: "boolean", default: false}
                      - {required: false, label: "text", name: "text", widget: "string"}
                  - {required: false, label: "image", name: "image", widget: "image"}
          # Image Gallery Content Section
          - label: "Image Gallery"
            name: "imageGallery"
            widget: "object"
            fields:
              - {required: false, label: "Component", name: "__component", widget: "hidden", default: "sections.image-gallery"}
              - {required: false, label: "Title", name: "Title", widget: "string"}
              - {required: false, label: "ImagesPerLine", name: "ImagesPerLine", widget: "number"}
              - label: "imageWithLink"
                name: "imageWithLink"
                widget: "list"
                fields:
                  - {required: false, label: "imageUrl", name: "imageUrl", widget: "image"}
                  - label: "targetLink"
                    name: "targetLink"
                    widget: "object"
                    fields:
                      - {required: false, label: "url", name: "url", widget: "string"}
                      - {required: false, label: "newTab", name: "newTab", widget: "boolean", default: false}
                      - {required: false, label: "text", name: "text", widget: "string"}
          # Rich Text Content Section
          - label: "Rich Text"
            name: "richText"
            widget: "object"
            fields:
              - {required: false, label: "Component", name: "__component", widget: "hidden", default: "sections.rich-text"}
              - {required: false, label: "Content", name: "content", widget: "text"}
          # Video Landing Page Content Section
          - label: "Video Landing Page"
            name: "videoLandingPage"
            widget: "object"
            fields:
              - {required: false, label: "Component", name: "__component", widget: "hidden", default: "sections.video-landing-page"}
              - {required: false, label: "title", name: "title", widget: "string"}
              - {required: false, label: "label", name: "label", widget: "string"}
              - {required: false, label: "description", name: "description", widget: "text"}
              - {required: false, label: "smallTextWithLink", name: "smallTextWithLink", widget: "text"}
              - label: "videoURLs"
                name: "videoURLs"
                widget: "list"
                fields:
                  - {required: false, label: "url", name: "url", widget: "string"}
                  - {required: false, label: "newTab", name: "newTab", widget: "boolean", default: false}
                  - {required: false, label: "text", name: "text", widget: "string"}
              - label: "InlineFeatures"
                name: "InlineFeatures"
                widget: "list"
                fields:
                  - {required: false, label: "title", name: "title", widget: "string"}
                  - {required: false, label: "description", name: "description", widget: "text"}
                  - {required: false, label: "Target url", name: "url", widget: "string"}
                  - {required: false, label: "image", name: "image", widget: "image"}
          # Wide Hero Content Section
          - label: "Wide Hero"
            name: "wideHero"
            widget: "object"
            fields:
              - {required: false, label:"Component", name: "__component", widget: "hidden", default: "sections.wide-hero"}
          # Wide Video Content Section
          - label: "Wide Video"
            name: "wideVideo"
            widget: "object"
            fields:
              - {required: false, label:"Component", name: "__component", widget: "hidden", default: "sections.wide-video"}
              - {required: false, label: "title", name: "title", widget: "string"}
              - {required: false, label: "label", name: "label", widget: "string"}
              - {required: false, label: "description", name: "description", widget: "text"}
              - {required: false, label: "youtubeEmbedUrl", name: "youtubeEmbedUrl", widget: "string"}
              - {required: false, label: "videoUrl", name: "videoUrl", widget: "string"}
              - {required: false, label: "richText", name: "richText", widget: "text"}
              - {required: false, label: "video", name: "video", widget: "hidden", default:""}


      - {required: false, label: "Status", name: "status", widget: "hidden", default: "published"}
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {required: false, label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {required: false, label: "Title", name: "title", widget: "string"}
      - {required: false, label: "Publish Date", name: "date", widget: "datetime"}
      - {required: false, label: "Featured Image", name: "thumbnail", widget: "image"}
      - {required: false, label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {required: false, label: "Body", name: "body", widget: "markdown"}
  - name: "article" # Used in routes, e.g., /admin/collections/blog
    label: "Articles" # Used in the UI
    label_singular: "Article"
    folder: "_posts/article" # The path to the folder where the documents are stored
    format: 'json'
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {required: false, label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {required: false, label: "Title", name: "title", widget: "string"}
      - {required: false, label: "Publish Date", name: "date", widget: "datetime"}
      - {required: false, label: "Featured Image", name: "thumbnail", widget: "image"}
      - {required: false, label: "Excerpt", name: "excerpt", widget: "markdown"}
      - {required: false, label: "Body", name: "body", widget: "markdown"}
