backend:
  name: git-gateway
  branch: main # Branch to update 
media_folder: "public/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/uploads" # The src attribute for uploaded media