

###
### Reusable Fields and Components
###
#_________________________________________ Button Link
buttonLink_component: &buttonLink_component                
  - {required: false, label: "url", name: "url", widget: "string"}
  - {required: false, label: "newTab", name: "newTab", widget: "boolean", default: false}
  - {required: false, label: "text", name: "text", widget: "string"}
  - {required: false, label: "type", name: "type", widget: "select", options: ["primary", "secondary"]}

#______________________ Description
desc_field: &desc_field {required: false, label: "label", name: "label", widget: "string"}
#________________________ Label
label_field: &label_field {required: false, label: "description", name: "description", widget: "text"}
#________________________________Link
link_component: &link_component                
  - {required: false, label: "url", name: "url", widget: "string"}
  - {required: false, label: "newTab", name: "newTab", widget: "boolean", default: false}
  - {required: false, label: "text", name: "text", widget: "string"}
#________________________________Meta
meta_component: &meta_component
  - {label: "Meta Title", name: "metaTitle", widget: "string"}
  - {required: false, label: "metaDescription:", name: "metaDescription:", widget: "text"}
  - {required: false, label: "twitterCardType:", name: "twitterCardType:", widget: "string", default: "summary"}
  - {required: false, label: "twitterUsername:", name: "twitterUsername:", widget: "string"}
  - {required: false, label: "shareImage", name: "shareImage", widget: "image"}
#___________________________________ Metadata Section
metadata_section: &metadata_section
  label: "Metadata"
  name: "metadata"
  widget: "object"
  required: false
  fields: *meta_component
#_________________________ Plan Component
plan_component: &plan_component
  label: "plan"
  name: "plan"
  widget: "object"
  fields:
    - *desc_field
    - label: "features"
      widget: "list"
      default: []
      fields:
        - {label: "name", name: "name", widget: "string"}
    - {label: "Is recommended?", name: "isRecommended", widget: "boolean", default: false }
    - {label: "Price", name: "price", widget: "number", value_type: "int" }
    - {label: "Price Period", name: "pricePeriod", widget: "string"}
#_________________________ Title
title_field: &title_field {required: false, label: "title", name: "title", widget: "string"}
##//////////////////////////////////////////////////////////////////////////////////////////////#
###
### Content Sections
###
#__________________________ Bottom Actions Content Section
bottom_actions: &bottom_actions
  label: "Bottom Actions"
  name: "bottomActions"
  widget: "object"
  fields:
    - {required: false, label: "Component", name: "__component", widget: "hidden", default: "sections.bottom-actions"}
    - *title_field
    - label: "buttons"
      name: "buttons"
      widget: "list"
      default: []
      fields: *buttonLink_component
#__________________________ Featured Row Content Section
feature_rows: &feature_rows  
  label: "Feature Rows"
  name: "featureRows"
  widget: "object"
  fields:
    - {required: false, label: "Component", name: "__component", widget: "hidden", default: "sections.feature-rows-group"}
    - label: "Features"
      name: "features"
      widget: "list" 
      default: []
      fields:
        - *title_field
        - *desc_field
        - label: "target link"
          name: "link"
          widget: "object"
          fields: *link_component
#____________________________Image Gallery Content Section
image_gallery: &image_gallery
  label: "Image Gallery"
  name: "imageGallery"
  widget: "object"
  fields:
    - {required: false, label: "Component", name: "__component", widget: "hidden", default: "sections.image-gallery"}
    - {required: false, label: "Title", name: "Title", widget: "string"}
    - {required: false, label: "ImagesPerLine", name: "ImagesPerLine", widget: "number"}
    - label: "imageWithLink"
      name: "imageWithLink"
      widget: "list"
      fields:
        - {required: false, label: "imageUrl", name: "imageUrl", widget: "image"}
        - label: "targetLink"
          name: "targetLink"
          widget: "object"
          fields: *link_component
#_____________________ On Page Anchor Content Section
on_page_anchor: &on_page_anchor
  label: "Anchor"
  name: "anchor"
  widget: "object"
  fields:
    - {required: false, label: "Component", name: "__component", widget: "hidden", default: "sections.on-page-anchor"}
    - {label: "Anchor ID", name: "anchorID", widget: "string"}
#_____________________ Pricing Content Section
pricing: &pricing
  label: "Rich Text"
  name: "richText"
  widget: "object"
  fields:
    - {required: false, label: "Component", name: "__component", widget: "hidden", default: "sections.pricing"}
    - *title_field
    - label: "Plans"
      name: "plans"
      widget: "list"
      fields: 
        - *plan_component
#_____________________ Rich Text Content Section
rich_text: &rich_text
  label: "Rich Text"
  name: "richText"
  widget: "object"
  fields:
    - {required: false, label: "Component", name: "__component", widget: "hidden", default: "sections.rich-text"}
    - {required: false, label: "Content", name: "content", widget: "text"}
#______________________________ Video Landing Page Content Section
video_landing_page: &video_landing_page
  label: "Video Landing Page"
  name: "videoLandingPage"
  widget: "object"
  fields:
    - {required: false, label: "Component", name: "__component", widget: "hidden", default: "sections.video-landing-page"}
    - *title_field
    - *label_field
    - *desc_field
    - {required: false, label: "smallTextWithLink", name: "smallTextWithLink", widget: "text"}
    - label: "videoURLs"
      name: "videoURLs"
      widget: "list"
      fields: *link_component
    - label: "InlineFeatures"
      name: "InlineFeatures"
      widget: "list"
      fields:
        - *title_field
        - *desc_field
        - {required: false, label: "Target url", name: "url", widget: "string"}
        - {required: false, label: "image", name: "image", widget: "image"}
#____________________ Wide Hero Content Section
wide_hero: &wide_hero
  label: "Wide Hero"
  name: "wideHero"
  widget: "object"
  fields:
    - {required: false, label:"Component", name: "__component", widget: "hidden", default: "sections.wide-hero"}
#______________________ Wide Video Content Section
wide_video: &wide_video
  label: "Wide Video"
  name: "wideVideo"
  widget: "object"
  fields:
    - {required: false, label:"Component", name: "__component", widget: "hidden", default: "sections.wide-video"}
    - *title_field
    - *label_field
    - *desc_field
    - {required: false, label: "youtubeEmbedUrl", name: "youtubeEmbedUrl", widget: "string"}
    - {required: false, label: "videoUrl", name: "videoUrl", widget: "string"}
    - {required: false, label: "richText", name: "richText", widget: "text"}
    - {required: false, label: "video", name: "video", widget: "hidden", default:""}
##/////////////////////////////////////////////////////////////////////////////////////////////////##

backend:
  name: git-gateway
  branch: main # Branch to update

logo_url: 'https://www.aviertechnologies.com/assets/avier-logo.png'
media_folder: "public/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/uploads" # The src attribute for uploaded media
collections:
  - name: "page" 
    create: true
    folder: "_posts/page"
    format: 'json'
    label: "Page"
    slug: "{{fields.slug}}"
    fields:
      - {required: false, label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - *title_field
      - {label: "Slug", name: "slug", widget: "string"}
      - *metadata_section
      - label: "Content Sections"
        name: "contentSections"
        widget: "list"
        typeKey: "contentSectionType"
        types:
          - *wide_hero
          - *wide_video
          - *feature_rows
          - *rich_text
          - *bottom_actions
          - *image_gallery
          - *on_page_anchor
          - *pricing
          - *video_landing_page
      - {required: false, label: "Status", name: "status", widget: "hidden", default: "published"}
